version: '3'

services:
  reviews:
    build: ./
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    image: clonebnb-reviews-db:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password